Support slicing sub image
VisualMeaning/tile-split pull request #21
Opened 2024-06-25 15:05 UTC by tracivar

- Add argument `--parentzoomlevel` and `--indexforzoom`. If a valid `parentzoomlevel` value is provided, `zoomrange` and `targetrange` values will be ignored, it will slice all the tiles for the current `zoomlevel` value.  For example, for the four level 5 sub images from one level 5 image, `--zoomlevel` should be 5, `--parentzoomlevel` should be 6, and `--indexforzoom` should be a number in 0-3. It will slice 1024 tiles for each input image and give them appropriate naming. Running all four of them should output the same results as slicing all the tiles for one level 6 input image.
- Replace `startzoomrangetoslice` and `endzoomrangetoslice` to be `zoomrangetoslice`, `starttargetrange` and `endtargetrange` to be `targetrangetoslice` in config to clean up.

https://visual-meaning.atlassian.net/browse/SMP-2392

2024-06-26 13:19 UTC, alightwing requested changes
I've gone through this on a pad of paper to prove out the overall method and I think it's fine, but there's a couple of bugs that need to be fixed before we can land this.

2024-06-26 13:19 UTC, alightwing commented on src/config.rs
> +                    indexforzoom,
There's no restrictions on `indexforzoom`. This means that if I have `parentzoomlevel` of 2, and `zoomlevel` of 1 (implying 4 subimages with Morton indexes between 0 and 3), I can still put in `--indexforzoom 255` and get some wacky tile numbering out the other end.

We can fairly assume that if the parent zoom level is 2 and the sub image is zoom level 1, then all of the other subimages will be zoom level 1 and there will be 4 of them, and so putting in a `indexforzoom` that's larger than 3 should throw some sort of error.

2024-06-26 13:19 UTC, alightwing commented on src/image.rs
> +                    x = (coord.0 + (tileimage_coord.0 * 32)) as u32,
This hardcoded multiplier assumes that the subimages are always going to be level 5 (32x32 tiles), and fun things happen if you try to use smaller subimages. Not sure how to write this in rust, but what the multiplier should actually be is `2 << zoomlevel`.

2024-06-27 15:21 UTC, tracivar commented
Thanks for the feedback! The issues were spot on.

2024-06-28 09:04 UTC, alightwing approved these changes
Thanks! The last thing to do is to updated the Readme - there's a code chunk in there which is a dump of `tile-split --help` which should be replaced.

2024-06-28 09:04 UTC, alightwing commented on src/image.rs
> -        let morton_idx_max = width_in_tiles * height_in_tiles;
This is probably fine? There must be a reason why we had the functionality to slice non-square images before (I think maybe we had more ambitious plans for the sub-region stuff) but I don't think it hurts to take it out now.

2024-06-28 09:35 UTC, merged